@Library('vars') _
pipeline{
    agent any

    environment {
        IMAGE_NAME="redaeid/kubernets-app_web-app"
        DEPLOYMENT_FILE="deployment.yaml"
        Docker_Credentials_ID='dockerHub-credentials'
        API_SERVER='APIServer'
        SERVICEACCOUNT_TOKEN='ServiceAccount-Token'
    }

    stages {
        stage('Run Unit Tests') {
            steps {
                dir('ci-cd/lab22/Jenkins_App') {
                    buildApp()
                }
            }
        }
       
        stage('Build Docker Image') {
            steps {
                dir('ci-cd/lab22/Jenkins_App') {
                buildAndPushImage(IMAGE_NAME,Docker_Credentials_ID)
            }
        }}
        stage('Docker Image Security Scan') {
         steps {
             script {
                 echo "Scanning Docker image with Trivy..."

                 sh "trivy image $IMAGE_NAME:$BUILD_NUMBER || true"
                 

                
             }
         }
            }       

       
        stage('Delete Local Docker Image') {
            steps {
                sh "docker rmi $IMAGE_NAME:$BUILD_NUMBER || true"
            }
        }
        stage('Update Deployment File') {
            steps {
                dir('ci-cd/lab22/Jenkins_App') {
                sh """
                    sed -i 's|image: .*|image: $IMAGE_NAME:$BUILD_NUMBER|' $DEPLOYMENT_FILE
                """
            }}
        }
        stage('Deploy to Kubernetes') {
            
            steps {
                dir('ci-cd/lab22/Jenkins_App') {
                deployOnK8S(API_SERVER,SERVICEACCOUNT_TOKEN)
            }
        }
        }
        
         
    }
    post {
          always {
            echo "Cleaning up workspace..."
        
    }
        success{
            echo "Pipeline succeeded."
        }
        failure{
            echo "Pipeline failed."
        }
    }


}